run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
  skip-files:
    - ".*\\.pb\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes: github.com/denysvitali/git-cc
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  depguard:
    rules:
      main:
        deny:
          # Allow all standard library packages
          - pkg: "^std$"
          # Allow all project packages
          - pkg: "^github.com/denysvitali/git-cc"
          # Allow commonly used third-party packages for this type of application
          - pkg: "^github.com/charmbracelet/bubbletea$"
            desc: "Bubble Tea TUI framework"
          - pkg: "^github.com/charmbracelet/bubbles"
            desc: "Bubble Tea component library"
          - pkg: "^github.com/charmbracelet/lipgloss$"
            desc: "Lipgloss styling library"
          - pkg: "^github.com/go-git/go-git/v5"
            desc: "Git operations library for tests"

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - mnd

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - mnd
        - nakedret

    # Exclude known linter issues
    - text: "weak cryptographic primitive"
      linters:
        - gosec

    # Exclude shadow checking on err variables
    - text: "shadow: declaration of \"err\""
      linters:
        - govet

    # Allow unused variables in certain contexts
    - text: "unused"
      linters:
        - unused

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0