# golangci-lint v2 configuration

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true

output:
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  shadow:
    check-shadowing: true
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes: github.com/denysvitali/git-cc
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - hugeParam
  depguard:
    rules:
      main:
        allow:
          - "$gostd"
          - "github.com/denysvitali/git-cc"
          - "github.com/charmbracelet/bubbletea"
          - "github.com/charmbracelet/bubbles"
          - "github.com/charmbracelet/lipgloss"
          - "github.com/go-git/go-git/v5"

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - copyloopvar
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - mnd

issues:
  exclude-dirs:
    - vendor
  exclude-files:
    - ".*\\.pb\\.go$"
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - mnd
        - nakedret

    # Exclude known linter issues
    - text: "weak cryptographic primitive"
      linters:
        - gosec

    # Exclude shadow checking on err variables
    - text: "shadow: declaration of \"err\""
      linters:
        - govet

    # Allow unused variables in certain contexts
    - text: "unused"
      linters:
        - unused

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0